# Generated by Django 3.1.7 on 2021-03-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP_database_backend', '0003_auto_20210315_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Intern', 'Intern')], max_length=20, null=True),
        ),
    ]
